### ISSUE TITLE
Revisions Page: Displaying list of all edits

### ISSUE THREAD

**Issue by echteinfachtv** [svivian/q2a-edit-history#12]
Hi Scott, just wanted to give you the new code that you can add to qa-edh-revisions.php, after line 56 "$this->recent_edits( $qa_content );" to display all edits: 

```
/* eetv added */
// retrieve URL variable
if( isset($_GET['show']) ) {
    $showMode = (int) $_GET['show'];
}
else {
    $showMode = 0; // default
}

// showModes
// 0 - default: show only questions, hides admin
// 1 - show only questions, includes admin
// 2 - show questions+answers, hides admin
// 3 - show questions+answers, includes admin

$days = 7; // last days to show from today
$showAdminEdits = false; 
if($showMode==1 || $showMode==3) $showAdminEdits=true;
$adminUserId = 1; // userid 1 should be admin!

// set language string herefile: qa_lang_html('edithistory/revision_list_title');
$qa_content['title'] = "Revision List (last ".$days." days)"; 

// return if not admin!
$level=qa_get_logged_in_level();
if ($level<QA_USER_LEVEL_ADMIN) {
    $qa_content['custom0']='<div>Zugriff nicht erlaubt</div>';
    return $qa_content;
}

// counter for custom html output
$c = 2;

// get list of posts
$queryRevisionList = qa_db_query_sub( 'SELECT postid, updated, title, tags, userid FROM ^edit_history
            WHERE updated > DATE_ADD(NOW(), INTERVAL -'.$days.' DAY)
            ORDER BY updated DESC');

$htmloutput = "<table>";
$htmloutput .= "<thead> <th>Date</th> <th>Post</th> <th>User</th> </thead>";

while ( ($row = qa_db_read_one_assoc($queryRevisionList,true)) !== null ) {
    // get link to revision post
    $activity_url = qa_path_to_root() . 'revisions/' . $row['postid'];
    // get link to original question 
    $post_url = qa_path_to_root() . qa_path_html( qa_q_request( $row['postid'], $row['title'] ) ); // $row['postid'];

    // workaround to get link to answer
    $display_post_url = "";
    if(strlen($post_url)>14) { 
        $display_post_url = '<a style="font-size:10px;color:#777;" href="'.$post_url.'">see live version</a>';
    }



    // if anonymous user edits his post then userid is NULL, catch it
    if($row['userid'] == $adminUserId && !$showAdminEdits) {
        // do not show admin edits
        continue;
    }
    else if(!isset($row['title']) && ($showMode==1 || $showMode==0) ) {
        // do not show answers, answers do not have title set
        continue;
    }
    // anonymous user
    else if($row['userid'] === NULL) {
        $revLink = isset($row['title']) ? $row['title'] : "Answer was edited";
        // display date as before x time
        $updateTime = implode('', qa_when_to_html( strtotime($row['updated']), qa_opt('show_full_date_days')));
        $htmloutput .= '<tr> <td>'.$updateTime.'</td> 
                             <td><a href="'.$activity_url.'">'.$revLink.'</a> <br />'.$display_post_url.'</td> 
                             <td>anonymous</td></tr>';
    }               
    else {
        // get user details (display avatar and name)
        $username = qa_db_read_all_assoc(qa_db_query_sub('SELECT handle FROM ^users WHERE userid = #',$row['userid']), 'handle');
        $user = qa_db_select_with_pending( qa_db_user_account_selectspec($username, false) );
        $revLink = isset($row['title']) ? $row['title'] : "Answer was edited";
        // display date as before x time
        $updateTime = implode('', qa_when_to_html( strtotime($row['updated']), qa_opt('show_full_date_days')));
        $htmloutput .= '<tr> <td>'.$updateTime.'</td> 
                             <td><a href="'.$activity_url.'">'.$revLink.'</a> <br />'.$display_post_url.'</td> 
                             <td>'. qa_get_user_avatar_html($user['flags'], $user['email'], $user['handle'], $user['avatarblobid'], $user['avatarwidth'], $user['avatarheight'], qa_opt('avatar_users_size'), false) . " " . qa_get_one_user_html($user['handle'], false).'</td></tr>';
    }
}

$htmloutput .= "</table>";

/* output into theme */
// admin options
$qa_content['custom'.++$c] = '<p>Options: <a href="?show=0">all Q (without admin)</a> | <a href="?show=1">all Q (with admin)</a> | ';
$qa_content['custom'.++$c] = '<a href="?show=2">all Q+A (without admin)</a> | <a href="?show=3">all Q+A (with admin)</a></p>';

// revision list
$qa_content['custom'.++$c] = '<div class="revisionList" style="border-radius:0; margin-top:-2px; min-height:350px;">';          
$qa_content['custom'.++$c] = $htmloutput;           
$qa_content['custom'.++$c] = '</div>'; // end revisionList

// custom css for qa-main
$qa_content['custom'.++$c] = '<style type="text/css">.qa-main { margin:20px 0 0 60px; width:640px; } table {width:616px;} thead,th { text-align:center;border:1px solid #CCC; background:#FFC; padding:8px; } td { padding:8px; } </style>';

return $qa_content;
/* END eetv added */
```

**Comment by q2apro** [comment]
Updated a bit: 

	// Display all recent edits
	private function recent_edits(&$qa_content)
	{
		$qa_content['title'] = qa_lang_html('edithistory/plugin_title');

		// check user is allowed to view edit history
		if (!$this->view_permit($qa_content))
			return;

		$qa_content['title'] = qa_lang_html('edithistory/main_title');
		// $qa_content['custom'] = '<p>This page will list posts that have been edited recently.</p>';
		
		/* q2apro added */
		// retrieve URL variable
		if( isset($_GET['show']) ) {
			$showMode = (int) $_GET['show'];
		}
		else {
			$showMode = 1; // default
		}
		
		// showModes
		// 0 - default: show only questions, hides admin
		// 1 - show only questions, includes admin
		// 2 - show questions+answers, hides admin
		// 3 - show questions+answers, includes admin
		
		$days = 3; // last days to show from today
		$showAdminEdits = false; 
		if($showMode==1 || $showMode==3) $showAdminEdits=true;
		$adminUserId = 1; // userid 1 should be admin!
		
		// set language string herefile: qa_lang_html('edithistory/revision_list_title');
		$qa_content['title'] = "Revisionsliste (".$days." Tage)"; 

		// return if not admin!
		$level=qa_get_logged_in_level();
		if($level < QA_USER_LEVEL_EDITOR) { // QA_USER_LEVEL_EXPERT
			$qa_content['error'] = 'Access not allowed';
			return $qa_content;
		}
		// for admin options to delete entry
		$isadmin = ($level >= QA_USER_LEVEL_ADMIN);
		
		// init output
		$output = '';
		
		// delete edit entry of post that is passed by admin
		if( isset($_GET['delete']) && isset($_GET['updated']) && ($level >= QA_USER_LEVEL_ADMIN) ) {
			$postid = $_GET['delete'];
			$updated = $_GET['updated'];
			qa_db_query_sub('DELETE FROM ^edit_history
								WHERE postid = $
								AND updated = $
							', $postid, $updated);
			$qa_content['custom0'] = '<div>Edit deleted: '.$postid.' / timestamp: '.$updated.'<br /><br /> <a href="'.qa_path('revisions').'">back to revisions</a> </div>';
			return $qa_content;
		}
		
		
		// get list of posts
		$queryRevisionList = qa_db_query_sub( 'SELECT postid, updated, title, tags, userid FROM ^edit_history
					WHERE updated > DATE_ADD(NOW(), INTERVAL -'.$days.' DAY)
					ORDER BY updated DESC');
	
		$htmloutput = "<table>";
		$htmloutput .= "<thead> <th>Zeit</th> <th>Bearbeitete Frage</th> <th>Editor</th> </thead>";
		
		while ( ($row = qa_db_read_one_assoc($queryRevisionList,true)) !== null ) {
			// get link to revision post
			$activity_url = qa_path_to_root() . 'revisions/' . $row['postid'];
			// get link to original question 
			$post_url = qa_path_to_root() . qa_path_html( qa_q_request( $row['postid'], $row['title'] ) ); // $row['postid'];
			
			// workaround to get link to answer
			$display_post_url = '';
			if(strlen($post_url)>14) { 
				// get new title of recent question
				$getQtitle = qa_db_read_one_value( qa_db_query_sub("SELECT title FROM `^posts` WHERE `postid` = # LIMIT 1", $row['postid']) );
				$qTitle = isset($getQtitle) ? $getQtitle : '';
				// get correct public URL
				$question_url = qa_path_html(qa_q_request($row['postid'], $qTitle), null, qa_opt('site_url'), null, null);
				$display_post_url = '&raquo; <a target="_blank" href="'.$question_url.'">'.$qTitle.'</a>'; // &raquo;
			}
			
			// if anonymous user edits his post then userid is NULL, catch it
			if($row['userid'] == $adminUserId && !$showAdminEdits) {
				// do not show admin edits
				continue;
			}
			else if(!isset($row['title']) && ($showMode==1 || $showMode==0) ) {
				// do not show answers, answers do not have title set
				continue;
			}
			// anonymous user
			else if($row['userid'] === NULL) {
				$revLink = isset($row['title']) ? $row['title'] : "Answer was edited";
				// display date as before x time
				$updateTime = implode('', qa_when_to_html( strtotime($row['updated']), qa_opt('show_full_date_days')));
				$htmloutput .= '<tr> <td>'.$updateTime.'</td> 
									 <td style="font-size:11px;"><a target="_blank" href="'.$activity_url.'">'.$revLink.'</a> <br />'.$display_post_url.'</td> 
									 <td>anonymous</td></tr>';
			}				
			else {
				// admin
				$delOption = '';
				if($isadmin) {
					$delOption = '<br /><a style="font-size:10px;color:#F99;" href="'.qa_path('revisions').'/?delete='.$row['postid'].'&updated='.$row['updated'].'">delete entry</a>';
				}
				// get user details (display avatar and name)
				$username = qa_db_read_all_assoc(qa_db_query_sub('SELECT handle FROM ^users WHERE userid = #',$row['userid']), 'handle');
				$user = qa_db_select_with_pending( qa_db_user_account_selectspec($username, false) );
				$revLink = isset($row['title']) ? $row['title'] : "Answer was edited";
				// display date as before x time
				$updateTime = implode('', qa_when_to_html( strtotime($row['updated']), qa_opt('show_full_date_days')));
				$htmloutput .= '<tr> <td style="font-size:11px;">'.$updateTime.'</td> 
									 <td style="font-size:11px;"><a style="color:#C55;" target="_blank" href="'.$activity_url.'">REV: '.$revLink.'</a> <br />'.$display_post_url.'</td> 
									 <td style="font-size:11px;">'. qa_get_user_avatar_html($user['flags'], $user['email'], $user['handle'], $user['avatarblobid'], $user['avatarwidth'], $user['avatarheight'], qa_opt('avatar_users_size'), false) . " " . qa_get_one_user_html($user['handle'], false). $delOption . '</td></tr>';
			}
		}
		
		$htmloutput .= "</table>";
		
		/* output into theme */
		// filter entries options if URL ?admin=1 is set
		if($isadmin && isset($_GET['admin'])) {
			$output .= '<p>Options: <a href="?show=0">all Q (without admin)</a> | 
						<a href="?show=1">all Q (with admin)</a> | 
						<a href="?show=2">all Q+A (without admin)</a> | 
						<a href="?show=3">all Q+A (with admin)</a>
						</p>';
		}
		
		// revision list
		$output .= '<div class="revisionList" style="border-radius:0; margin-top:-2px; min-height:350px;">';			
		$output .= $htmloutput;			
		$output .= '</div>'; // end revisionList
		
		// custom css for qa-main
		$output .= '<style type="text/css">.qa-main { margin:0 0 0 10px; } table {width:98%;} thead,th { text-align:center;border:1px solid #CCC; background:#FFC; padding:8px; } td { padding:8px; border:1px solid #CCC; } table tr:nth-of-type(even){background-color:#DDD} </style>';
		
		$qa_content['custom'] = $output;
		
		return $qa_content;
		/* END q2apro */
	}
