### ISSUE TITLE
"Edited" word should also be included in the link for showing the edits

### ISSUE THREAD

**Issue by gurjyot** [svivian/q2a-edit-history#16]
Currently only the time behaves as a link to show the edits, but actually the "edited" word should be linked to the edits page. 
To remove confusion I have seen in stackoverflow, there both the word "edited" and time is lined to the edits page. 
If edited word is linked to that edits page then it will be easy for users to understand what that link would be for.

**Comment by svivian** [comment]
Actually the plugin used to do this but it was a bit messy for various reasons. Linking the date is clearer and more consistent.
